version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9093:9093"
    expose:
      - "9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAME_INSIDE: INSIDE
      KAFKA_LISTENER_PORT: 9093
      KAFKA_LISTENER_INTERFACE: eth0
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_NAME_EXTERNAL: EXTERNAL
      KAFKA_ADVERTISED_LISTENER: INSIDE
      KAFKA_LISTENER_PORT_INTERNAL: 9093
      KAFKA_LISTENER_INTERNAL_PORT: 9093
  connect:
    image: debezium/connect:latest
    environment:
      BOOTSTRAP_SERVERS: kafka:9093
      GROUP_ID: "debezium"
      CONFIG_STORAGE_TOPIC: "debezium_config"
      OFFSET_STORAGE_TOPIC: "debezium_offset"
      LOGGING_LEVEL: "INFO"
      CONNECT_PLUGIN_PATH: /kafka/connect/debezium
      DEBEZIUM_OPTS: "-Ddebezium.snapshot.mode=initial"
    ports:
      - "8083:8083"
