version: '2'
services:
  zookeeper:
    image: bitnami/zookeeper:3.8.0  # Replace with the Bitnami Zookeeper image
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"

  kafka:
    image: bitnami/kafka:3.8.0  # Replace with the Bitnami Kafka image
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    ports:
      - "9092:9092"

  connect:
    image: debezium/connect:2.0  # Use a specific version of Debezium Connect
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=debezium
      - CONFIG_STORAGE_TOPIC=debezium_config
      - OFFSET_STORAGE_TOPIC=debezium_offset
      - CONNECT_PLUGIN_PATH=/kafka/connect
    ports:
      - "8083:8083"
